export interface Product {
  id: string;                    // GUID, generated by the scraper
  name: string;
  description: string;
  price: number;
  imageUrl: string;
  categoryName: string;
  availableAmount: number | null;
  createdAt: string;
  updatedAt: string;
}
