namespace Store.Scraper.Models;

// The scraper's own stored product entity — differs from the API shape
public class Product
{
    public Guid Id { get; set; }         // GUID, generated by the scraper
    public string Name { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;
    public decimal Price { get; set; }
    public string ImageUrl { get; set; } = string.Empty;
    public Guid CategoryId { get; set; }
    public string CategoryName { get; set; } = string.Empty;
    public int? AvailableAmount { get; set; }
    public DateTime CreatedAt { get; set; }
    public DateTime UpdatedAt { get; set; }
}
